version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_REGION=us-east-1
